version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build --prod
        - yarn run scully 
  artifacts:
    baseDirectory: dist/scully-amplify-test
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
